### ISSUE TITLE
template_icon_view doesn't display icon names correctly when using bip.

### ISSUE THREAD

**Issue by strike-digital** [coreprocess/3dn-bip#51]
When using bip to load previews, the labels in ```layout.template_icon_view(show_labels=True)``` display very incorrectly:

![image](https://user-images.githubusercontent.com/59890307/134077240-07c4b351-e9db-47cf-acf7-fa3d10842932.png)

Here, the icons' names should just display their index:
```
for index, path in enumerate(img_paths):
    name = path.name
    icon = pcoll.load_safe(name, str(path), "IMAGE")
    _at_tree_previews.append((name, str(index), name, icon.icon_id, index))
```
where ```_at_tree_previews``` is the return value of the EnumProperty items callback

I also tried this on the example addon provided, and the same problem occurred.
To reproduce this, just set ```show_labels=True``` in the ```template_icon_view``` method in the example addon

I'm not 100% sure this is caused by bip, but I couldn't replicate it by using the normal ```bpy.utils.previews``` method. (Also, just as a side note, otherwise, this is amazing, and it solves a problem I've had for a while with the default blender previews :)

**Comment by bonjorno7** [comment]
This is a problem with Blender and dynamic enums.
Sometimes the approach you've taken works, other times it doesn't.
You need to keep a global Python reference to the items being displayed

**Comment by strike-digital** [comment]
Ok, thanks for the info, that's good to know. But the above code is already using a global variable...
Also, this happens with the showcase addon, which is also using a global variable for the items:
![image](https://user-images.githubusercontent.com/59890307/134181978-ee432c3e-7ad5-4a8e-acdc-d47da159080b.png)

Is there any other way to fix this problem?

**Comment by coreprocess** [comment]
@strike-digital Here is some code that works too and does not produce an endless list but instead grows the dictionary to an upper limit.

```py
_item_map = dict()

def _make_item(id, name, descr, preview_id, uid):
    lookup = f"{str(id)}\0{str(name)}\0{str(descr)}\0{str(preview_id)}\0{str(uid)}"
    if not lookup in _item_map:
        _item_map[lookup] = (id, name, descr, preview_id, uid)
    return _item_map[lookup]

def generate_list_example():
    l = []
    for i in range(10):
        l.append(_make_item(i, 'name' + str(i), 'descr' + str(i), 0, i))
    return l
```

**Comment by strike-digital** [comment]
That's great! I have no idea how you came up with that, but it works like a charm. Thanks!
